# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vkAlissia-2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift', '= 5.3.5'
  pod 'SDWebImage', '= 5.8.4'

  # Pods for vkAlissia-2

end
